email
fintegrate-practicom/infra pull request #13
Opened 2024-06-04 11:17 UTC by yaelKlain

2024-06-17 22:43 UTC, chanakamin commented on src/business/services/business.service.ts
> +const code="4244"
מה זה??

2024-06-17 22:43 UTC, chanakamin commented on src/business/services/business.service.ts
> +    save= await newBusiness.save();
מאיפה המשתנה save מגיע?

2024-06-17 22:45 UTC, chanakamin requested changes
מצוין
תתקני קונפליקטים ותריצי lint

2024-06-18 11:03 UTC, RutheHershler approved these changes

2024-06-18 11:23 UTC, yaelKlain reviewed
ביצעתי שינויים

2024-06-18 11:24 UTC, shirashtub approved these changes

2024-06-18 11:55 UTC, chanakamin approved these changes

2024-06-18 11:56 UTC, merged