add deploy.yml
fintegrate-practicom/infra pull request #52
Opened 2024-08-06 12:48 UTC by 475michalk

2024-08-06 12:50 UTC, michalzrian submitted a review, later dismissed

2024-08-06 12:58 UTC, nechamaLearn requested changes
אני רוצה שהרפו יהיה בשם משותף לכולם
אבל בשום אופן לא communnication

2024-08-06 12:58 UTC, nechamaLearn commented on .github/workflows/deploy.yml
> +  SERVICE: communication
!!!

2024-08-06 12:58 UTC, nechamaLearn commented on .github/workflows/deploy.yml
> +  REPO: communication
!!!

2024-08-06 12:58 UTC, nechamaLearn commented on .github/workflows/deploy.yml
> +  IMAGE: infrastructure-communication
!!!

2024-08-06 13:18 UTC, nechamaLearn submitted a review, later dismissed

2024-08-06 13:40 UTC, michalzrian submitted a review, later dismissed

2024-08-06 14:19 UTC, michalzrian approved these changes, later dismissed

2024-08-06 16:26 UTC, yiskaAvramsky approved these changes, later dismissed

2024-08-06 17:46 UTC, yiskaAvramsky approved these changes, later dismissed

2024-08-07 08:53 UTC, buzz-code commented on .github/workflows/deploy.yml
> +  SERVICE: ${{ github.event.repository.name }}
לא צריך את משתנה הסביבה הזה, אפשר להשתמש פשוט ב ${{ github.event.repository.name }}

2024-08-07 09:23 UTC, michalzrian approved these changes

2024-08-07 09:24 UTC, buzz-code approved these changes

2024-08-07 09:33 UTC, merged